name: Deploy to WordPress Theme

on:
  push:
    branches:
      - main  # Deploys when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          local-dir: "stove-theme/"  # ✅ Adjust this to your local folder name
          server-dir: "/wp-content/themes/blank-canvas-3/"  # ✅ Change to "blank-canvas" (or the correct folder name)
          timeout: 600
          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            **/README.md
